services:
  samba:
    image: ghcr.io/servercontainers/samba
    cap_add:
      - CAP_NET_ADMIN
    ports:
      - target: 445
        published: 445
        protocol: tcp
        mode: host
      - target: 139
        published: 139
        protocol: tcp
        mode: host
      - target: 137
        published: 137
        protocol: udp
        mode: host
      - target: 138
        published: 138
        protocol: udp
        mode: host
    environment:
      SAMBA_CONF_LOG_LEVEL: 1
      AVAHI_DISABLE: 1
      SAMBA_VOLUME_CONFIG_public: |
        [Shares]
         path = /homepi
         guest ok = yes
         guest only = yes
         read only = no
         browseable = yes
         force user = root
         create mask = 0666
         directory mask = 0777
    volumes:
      - ${HPI_LOCAL_DATA_PATH}:/homepi
