services:
  # gitea-db:
  #   image: postgres:17
  #   environment:
  #     # configtool managed
  #     - POSTGRES_PASSWORD=${GITEA_DATABASE_PASSWORD}
  #     # Portainer optional
  #     - POSTGRES_USER=${GITEA_DATABASE_USER:-gitea}
  #     - POSTGRES_DB=${GITEA_DATABASE_NAME:-gitea}
  #   networks:
  #     - webproxy-backend
  #   volumes:
  #     - ${HPI_LOCAL_DATA_PATH}/gitea/postgres_db:/var/lib/postgresql/data

  gitea-pgupgrade:
    image: pgautoupgrade/pgautoupgrade:latest
    environment:
      PGAUTO_ONESHOT: 'yes'
      POSTGRES_USER: ${GITEA_DATABASE_USER:-gitea}
      POSTGRES_PASSWORD: ${GITEA_DATABASE_PASSWORD}
    volumes:
      - ${HPI_LOCAL_DATA_PATH}/gitea/postgres_db:/var/lib/postgresql
    networks:
      - webproxy-backend
    deploy:
      replicas: 0
      restart_policy:
        condition: none

networks:
  webproxy-backend:
    external: true
