services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      - TZ=${HPI_TIME_ZONE}
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=change-me-now
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=https://auth.${HPI_DNS_DOMAIN}:${HPI_HTTPS_PORT}
    volumes:
      - ${HPI_LOCAL_DATA_PATH}/keycloak:/opt/keycloak/data
    networks:
      - webproxy-backend
    labels:
      caddy: auth.${HPI_DNS_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls.propagation_delay: 120s
      caddy.tls.dns: desec
      caddy.tls.dns.token: ${HPI_DESEC_TOKEN}
    deploy:
      labels:
        - homepage.group=Management  
        - homepage.name=Auth
        - homepage.icon=sh-keycloak
        - homepage.href=https://auth.${HPI_DNS_DOMAIN}:${HPI_HTTPS_PORT}/

networks:
  webproxy-backend:
    external: true
