services:
  acme-sh:
    image: neilpang/acme.sh:latest
    environment:
      - DEDYN_TOKEN=${HPI_DESEC_TOKEN}
      - LE_EMAIL=${HPI_PRIMARY_EMAIL}
      - LE_DNS_SLEEP=120
      - LE_RENEW_SKIP_RC=2
      - DOCKER_HOST=tcp://dockerproxy:2375
    networks:
      - webproxy-backend
    volumes:
      - ${HPI_LOCAL_DATA_PATH}/acme.sh/acme:/acme.sh
      - ${HPI_LOCAL_DATA_PATH}/acme.sh/certs:/certs
      - ./docker-entrypoint-certificates.sh:/docker-entrypoint-certificates.sh:ro
    configs:
      - source: certificates_acme_domain_list
        target: /run/config/certificates_acme_domain_list
        mode: 0444
    entrypoint: /docker-entrypoint-certificates.sh
    # cert issuance gets messed up when using the internal resolver
    dns:
      - 1.1.1.1
      - 1.0.0.1
    deploy:
      replicas: 0
      restart_policy:
        condition: none
      labels:
        - swarm.cronjob.enable=true
        # Start service every day at 3 AM
        - swarm.cronjob.schedule=0 3 * * *
        - swarm.cronjob.skip-running=true
      placement:
        constraints:
          - node.role == manager

networks:
  webproxy-backend:
    external: true

configs:
  certificates_acme_domain_list:
    external: true
