services:
  plex:
    image: plexinc/pms-docker
    ports:
      - 32401:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      # - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_UID=${HPI_APP_UID}
      - PLEX_GID=${HPI_APP_GID}
      - TZ=${HPI_TIME_ZONE}
      # - PLEX_CLAIM=  # Optional Plex claim token for automatic server association
      - ADVERTISE_IP=https://plex.${HPI_DNS_DOMAIN}:32400
    volumes:
      - ${HPI_LOCAL_DATA_PATH}/plex/config:/config
      - ${HPI_LOCAL_DATA_PATH}/plex/transcode:/transcode
      - ${HPI_LOCAL_DATA_PATH}/plex/media:/plex-media
    networks:
      - webproxy-backend
    labels:
      caddy: plex.${HPI_DNS_DOMAIN}:32400
      caddy.reverse_proxy: "{{upstreams 32400}}"
      caddy.tls.propagation_delay: 120s
      caddy.tls.dns: desec
      caddy.tls.dns.token: ${HPI_DESEC_TOKEN}
    deploy:
      labels:
        - homepage.group=Home  
        - homepage.name=Watch  
        - homepage.icon=sh-plex
        - homepage.href=https://plex.${HPI_DNS_DOMAIN}:32400/

networks:
  webproxy-backend:
    external: true
