services:
  shepherd:
    image: containrrr/shepherd
    environment:
      TZ: ${HPI_TIME_ZONE}
      # VAULT
      REGISTRY_USER: ${SHEPHERD_REGISTRY_USERNAME}
      REGISTRY_PASSWORD: ${SHEPHERD_REGISTRY_PASSWORD}
      VERBOSE: 'true'
      # Prevent Shepherd from updating its own task or the cron scheduler that launches it.
      IGNORELIST_SERVICES: 'update_shepherd homepi-critical_scheduler'
      FILTER_SERVICES: ''
      RUN_ONCE_AND_EXIT: 'true'
      IMAGE_AUTOCLEAN_LIMIT: 8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 2
      labels:
        - swarm.cronjob.enable=true
        # Start service every Friday at 5 AM
        - swarm.cronjob.schedule=0 5 * * 5
        - swarm.cronjob.skip-running=true
      placement:
        constraints:
          - node.role == manager
